# Generated by Django 4.1.3 on 2022-11-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0003_orders_alter_item_price_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'usd'), ('rub', 'rub')], max_length=3, null=True),
        ),
    ]
