# Generated by Django 4.1.3 on 2022-11-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0004_item_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'usd'), ('rub', 'rub')], max_length=3, null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'usd'), ('rub', 'rub')], max_length=3, null=True, verbose_name='Валюта'),
        ),
    ]
